### ISSUE TITLE
Rails 5

### ISSUE THREAD

**Issue by ajazshaik** [sriram15690/smsCountryGem#1]
can u tell me whether it work with rails 5 ? if possible can u share an sample app done using this gem

**Comment by sriram15690** [comment]
Hello,

The Gem was developed for Rails 4. I've not yet tested it with rails 5. I shall do it soon. 

Regarding, the Sample Application, the documentation provided with Gem is sufficient to understand. Can you please let me know in which aspect are u facing issues or problems ? I can help you out.
